### PR TITLE
Update SOCKS Version

### PR DESCRIPTION
**Pull request by knoxcard**
warning tor-request > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

### CODE REVIEW

**Comment by knoxcard** [comment]
Revision to title

**Comment by knoxcard** [comment]
This is an important update and should be updated immediately, there's been a ton of fixes and npm and yarn is telling me to upgrade.

Fixes incoming data flow issues. It's highly recommended to upgrade to this version if you're using 2.x.x
This fixes an issue with the 'receivebuffer' import.

https://github.com/JoshGlazebrook/socks/releases

**Comment by talmobi** [comment]
Halåj!

socks 2.x dropped agent bundling from itself so I merged your commit and switched to using `node-socks-proxy-agent` that also uses socks under the hood. However, `node-socks-proxy-agent` also uses 1.x currently so I forked it and migrated it to use socks v2 and published to scoped package `@talmobi/node-socks-proxy-agent` and issued a pull request https://github.com/TooTallNate/node-socks-proxy-agent/pull/16

I bumped the major version to 2.0.0 since socks v2 requires nodejs 6 and it would break older changes. Same thing will apply for `node-socks-proxy-agent`.

**Comment by talmobi** [comment]
Basically merged here: https://github.com/talmobi/tor-request/commit/506e025415484460d520d17d65cd0c1a4830914e

Not sure how this GitHub UI picks it up but I can only close it now ( used the terminal to merge etc ). You're showing up in the `contributors` though so I guess it worked, thanks for your help!

https://github.com/talmobi/tor-request/graphs/contributors

I think the 2.x issues are specific to 2.x and doesn't affect 1.x ( like the receive buffer ) etc -- but regardless I think it's a good idea to bump major version and support the latest socks version as well!

**Pull request closed without merging**
