### PR TITLE
Socks Proxy Agent - 4.0.1

### PR DESCRIPTION
**Pull request by knoxcard**
What do you think? Will this break anything?

### CODE REVIEW

**Comment by talmobi** [comment]
Halåj,

There's a small bug currently in that version, I've made a pull request here: https://github.com/TooTallNate/node-socks-proxy-agent/pull/18

Once that's merged I'll be happy to switch.

It doesn't really matter either way for now - only perhaps a small aesthetic inconsistency ;D

**Comment by knoxcard** [comment]
This should work now, changed socks to 4.0.1, they integrated your change! woohoo

**Comment by talmobi** [comment]
@knoxcard can you add the squiggly line `~` before the version as well?

**Comment by knoxcard** [comment]
Squiggles Added

**Pull request merged**
