### PR TITLE
Bump socks

### PR DESCRIPTION
**Pull request by knoxcard**
Bump socks

### CODE REVIEW

**Comment by knoxcard** [comment]
Strange, latest release displayed here states **2.3.2**...
https://www.npmjs.com/package/socks

The official repository declares it as **2.3.1**...
https://github.com/JoshGlazebrook/socks/releases

I set it to 2.3.2 and it has **no conflicts with the base branch**. ;-)

**Comment by talmobi** [comment]
2.3.2 just has some updates to npm ignore: https://github.com/JoshGlazebrook/socks/compare/2.3.1...master

Thanks for this, I'll take a look and run a few tests soon~

**Comment by talmobi** [comment]
I tested it and it works, but I've decided to remove the socks dependency because it's unnecessary -- since we actually rely entirely on `socks-proxy-agent` so we will defer to their internal `socks` version and we don't anymore need our own version of it.

To that end I've updated the package.json and package-lock.json to reflect this change.

**Comment by knoxcard** [comment]
@talmobi - nice work!

**Pull request merged**
