### PR TITLE
Support for Multiple SOCKSPorts

### PR DESCRIPTION
**Pull request by kauegimenes**
`var tr = new require('tor-request')();`

### CODE REVIEW

**Comment by talmobi** [comment]
Cool! I'll test and take a look this weekend!

**Comment by talmobi** [comment]
Been really busy as of late, will try and take a look asap.

**Comment by talmobi** [comment]
I'm unable to get this to work properly, tests keep failing, thoughts?

**Comment by knoxcard** [comment]
Check this out....this might be of help...

https://stackoverflow.com/questions/19043355/how-to-use-request-js-node-js-module-pools

**Comment by knoxcard** [comment]
Didn't know you could do this....rad!
```
var pool = new http.Agent(); //Your pool/agent
http.request({hostname:'localhost', port:80, path:'/', agent:pool});
request({url:"http://www.google.com", pool:pool });
```

**Comment by talmobi** [comment]
@knoxcard So this is already possible by specifying the agent option when using `request`?

https://github.com/request/request#requestoptions-callback

**Comment by knoxcard** [comment]
@talmobi - It would appear so!
I am going to try and experiment tonight, but to tell you the truth, this module already satisfies my current needs.  If one is using this module to scrap a site, I would not recommend opening 10+ simultaneous requests on the target machine, unless you feel like getting caught.  I know different IP's are being used though, so that would help resolve that issue.  Key point is you don't want to be too obvious, obviously. lol

Although, if this option works, it should be implemented into this package to allow the option to be able to do so at one's own risk.

**Comment by knoxcard** [comment]
Another interesting find...

https://www.npmjs.com/package/hyperquest

**Comment by talmobi** [comment]
Closing this due to old age, lack of updates and no clear usage design that could be implemented.

**Comment by knoxcard** [comment]
Good call, later when I have time, I'll write something up and submit a PR or update the wiki with a clear concise method of handling this, if I derive something significant.

**Comment by xAvarice** [comment]
This is my desired usage also, I would appreciate any further clarity or recommendation on this.

**Comment by talmobi** [comment]
@xAvarice What kind of use case do you have precisely?

You can change the SOCKS port using `tr.setTorAddress(...)` (defaults to 9050) before making the request.

**Comment by xAvarice** [comment]
Simply, I will have multiple "users" and I want their requests to all have different ips or as close that as possible (considering exit node limitations).

So request(user1, requestEtc) would have a different connection/session to request(user2, ...)...

Is this possible with user agent? Thank you for the fast reply! I very much appreciate your work here, not many others have attempted it.

**Comment by knoxcard** [comment]
I would run multiple instances of Tor on my linux box, each under a different port...9050, 9051, 9052, 9053, 9054.....9060.  Say 10 instances and each instance would have an IP address. If you had 100 users, 10 users would be under one instance and you would have 10 instances.

**Comment by xAvarice** [comment]
Yes, I have considered that but I have read it is recommended against and can be achieved without multiple TOR instances.

Also handling starting TOR instances when users increases is something I'm hoping isn't necessary.

**Comment by knoxcard** [comment]
https://github.com/znetstar/tor-router#readme

A JSON-RPC 2 TCP Server will listen on port 9077 by default. Using the rpc server the client can add/remove Tor instances and get a new identity (which includes a new ip address) while Tor Router is running.

Example (in node):
```

	const net = require('net');

	let client = net.createConnection({ port: 9077 }, () => {
		let rpcRequest = {
			"method": "createInstances",
			"params": [3], 
			"jsonrpc":"2.0", 
			"id": 1
		};
		client.write(JSON.stringify(rpcRequest));
	});

	client.on('data', (chunk) => {
		let rawResponse = chunk.toString('utf8');
		let rpcResponse = JSON.parse(rawResponse);
		console.log(rpcResponse)
		if (rpcResponse.id === 1) {
			console.log('Three instances have been created!')
		}
	})
```

**Comment by talmobi** [comment]
The user agent used in `tor-request` or any other http library just holds the configuration of where and how to connect (a SOCKS configuration to be more precise) to the `tor` instance itself.

Each `tor` instance establishes a connection to the tor network using black magic (not really, but from our perspective yes).

Establishing a connection to the tor network is expensive in terms of latency/network usage.

Every time you want a new "public ip" (a new tor exit node) you have to essentially restart the connection. And it's not feasible to do this very often and tor nodes can detect abuse.

`tor-request` just connects to the underlying `tor` service you have running. So getting 10 public tor ip's to rotate through you would have to be running 10 tor instances as well.

**Comment by xAvarice** [comment]
That is brilliant but I've already seen it, the reason I wanted to avoid it was:
"Tor an each request will be sent to a different instance in round-robin fashion. This can be used to increase anonymity, because each request will be sent on a different circuit and will most likely use a different exit-node"

I am trying to avoid ip addresses overlapping for each user, this seems to cause that due to the "round robin" nature whereas it does demonstrate my intent is possible? Am I mistaken?

**Comment by talmobi** [comment]
I don't think you can be certain that ip addresses will be different for each user. The tor exit nodes come and go and change as they please.

It's possible `tor` itself has some higher level API to control exit node shuffling that I'm not aware of other than what it does by default.

**Comment by xAvarice** [comment]
So I guess even if the ips overlap all that would give away about the users is that they are all using TOR, not necessarily that they are all the same person. I think I can accept that.

Thank you for your time.

**Pull request closed without merging**
